In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [45]:
data = pd.read_csv('exam1.csv')

In [46]:
data

   Youtube  guide result
0        0      0   fail
1        1      1   pass
2        1      0   pass
3        0      0   fail
4        0      0   fail
5        1      1   pass
6        0      1   fail
7        1      1   pass
8        1      0   fail
9        1      1   pass

In [47]:
data.result.value_counts()

result
fail    5
pass    5
Name: count, dtype: int64

In [48]:
entropy_results = -(5/10)*np.log2(5/10) -(5/10)*np.log2(5/10)
entropy_results

np.float64(1.0)

In [49]:
data.rename(columns = {'Youtube':'yt'}, inplace = True)

In [50]:
data

   yt  guide result
0   0      0   fail
1   1      1   pass
2   1      0   pass
3   0      0   fail
4   0      0   fail
5   1      1   pass
6   0      1   fail
7   1      1   pass
8   1      0   fail
9   1      1   pass

In [60]:
data[data.yt == 1]

   yt  guide result
0   0      0   fail
1   1      1   pass
2   1      0   pass
3   0      0   fail
4   0      0   fail
5   1      1   pass
6   0      1   fail
7   1      1   pass
8   1      0   fail
9   1      1   pass

In [61]:
entropy_results_yt_yes = -(5/6)*np.log2(5/6) -(1/6)*np.log2(1/6)
entropy_results_yt_yes

np.float64(0.6500224216483541)

In [62]:
data[data.yt == 0]

   yt  guide result
0   0      0   fail
3   0      0   fail
4   0      0   fail
6   0      1   fail

In [63]:
#zero

In [64]:
yt_entropy = (6/10) * entropy_results_yt_yes +  (4/10) * 0
yt_entropy

np.float64(0.39001345298901247)

In [65]:
info_yt = entropy_results - (6/10) * entropy_results_yt_yes -  (4/10) * 0
info_yt

np.float64(0.6099865470109875)

In [67]:
data[data.guide == 1]
data.head(10)

   yt  guide result
0   0      0   fail
1   1      1   pass
2   1      0   pass
3   0      0   fail
4   0      0   fail
5   1      1   pass
6   0      1   fail
7   1      1   pass
8   1      0   fail
9   1      1   pass

In [68]:
entropy_results_guide_yes = -(4/5)*np.log2(4/5) -(1/5)*np.log2(1/5)
entropy_results_guide_yes

np.float64(0.7219280948873623)

In [69]:
data[data.guide == 0]

   yt  guide result
0   0      0   fail
2   1      0   pass
3   0      0   fail
4   0      0   fail
8   1      0   fail

In [70]:
entropy_results_guide_no = -(1/5)*np.log2(1/5) -(4/5)*np.log2(4/5)
entropy_results_guide_no

np.float64(0.7219280948873623)

In [71]:
guide_entropy = (5/10) * entropy_results_guide_yes +  (5/10) * entropy_results_guide_no
guide_entropy

np.float64(0.7219280948873623)

In [72]:
info_guide = entropy_results - guide_entropy
info_guide

np.float64(0.2780719051126377)

In [73]:
print(info_yt)

0.6099865470109875

In [74]:
print(info_guide)

0.2780719051126377

In [76]:
from sklearn.preprocessing import LabelEncoder

In [77]:
le = LabelEncoder()
df = data
df.result = le.fit_transform(df.result)
df

   yt  guide  result
0   0      0       0
1   1      1       1
2   1      0       1
3   0      0       0
4   0      0       0
5   1      1       1
6   0      1       0
7   1      1       1
8   1      0       0
9   1      1       1

In [78]:
x = df[['yt','guide']]
y = df['result']

In [81]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz

In [82]:
dt = DecisionTreeClassifier(criterion='entropy')

In [83]:
dt.fit(x,y)

DecisionTreeClassifier(criterion='entropy')

In [84]:
export_graphviz(dt,'dt.tree',feature_names=['yt','guide'])

In [85]:
dt.predict([[1,1]])

C:\Users\Abdul\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [86]:
dt.score(x,y)

0.9